//! STOCKBACK ReceiptProver: Ed25519 attestation verifier on Arbitrum Stylus.
//!
//! Implements `IReceiptVerifier.verify(bytes32 digest, bytes attestation) -> bool`, the same
//! ABI as the Solidity `ECDSAAttestationVerifier`, so `ReceiptCommitmentRegistry` can use
//! either. `attestation = pubkey (32 bytes) || signature (64 bytes)`; the pubkey must be an
//! allowlisted attester and the signature must be a strict RFC 8032 Ed25519 signature over
//! the 32-byte EIP-712 claim digest.
//!
//! Why Stylus: the EVM has no Ed25519 precompile, so Solidity must implement SHA-512 and
//! curve25519 arithmetic in bytecode. Here it is compiled Rust. `benchmarks/` measures the
//! difference instead of assuming it.
//!
//! This contract only answers yes/no. It holds no funds and has no authority over rewards.
#![cfg_attr(not(any(test, feature = "export-abi")), no_main)]
extern crate alloc;

mod attestations;

use alloc::vec::Vec;
use stylus_sdk::{
    alloy_primitives::{Address, Bytes, FixedBytes},
    prelude::*,
};

sol_storage! {
    #[entrypoint]
    pub struct ReceiptProver {
        address owner;
        mapping(bytes32 => bool) attesters;
    }
}

#[public]
impl ReceiptProver {
    #[constructor]
    pub fn constructor(&mut self, owner: Address) -> Result<(), Vec<u8>> {
        if owner.is_zero() {
            return Err(b"zero owner".to_vec());
        }
        self.owner.set(owner);
        Ok(())
    }

    pub fn owner(&self) -> Address {
        self.owner.get()
    }

    pub fn is_attester(&self, pubkey: FixedBytes<32>) -> bool {
        self.attesters.get(pubkey)
    }

    pub fn set_attester(&mut self, pubkey: FixedBytes<32>, allowed: bool) -> Result<(), Vec<u8>> {
        if self.vm().msg_sender() != self.owner.get() {
            return Err(b"not owner".to_vec());
        }
        self.attesters.setter(pubkey).set(allowed);
        Ok(())
    }

    pub fn transfer_ownership(&mut self, new_owner: Address) -> Result<(), Vec<u8>> {
        if self.vm().msg_sender() != self.owner.get() {
            return Err(b"not owner".to_vec());
        }
        if new_owner.is_zero() {
            return Err(b"zero owner".to_vec());
        }
        self.owner.set(new_owner);
        Ok(())
    }

    /// IReceiptVerifier. Never reverts on bad input; returns false.
    pub fn verify(&self, digest: FixedBytes<32>, attestation: Bytes) -> bool {
        match attestations::split(&attestation) {
            Some((pk, sig)) => {
                self.attesters.get(FixedBytes(pk)) && attestations::verify(&digest.0, &pk, &sig)
            }
            None => false,
        }
    }

    /// Batch form used by the benchmark: true only if every (digest, attestation) pair verifies.
    pub fn verify_batch(&self, digests: Vec<FixedBytes<32>>, attestations: Vec<Bytes>) -> bool {
        digests.len() == attestations.len()
            && digests
                .iter()
                .zip(attestations.iter())
                .all(|(d, a)| self.verify(*d, a.clone()))
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use stylus_sdk::testing::*;

    // Generated by `node tools/attester.mjs vector` (Node crypto, RFC 8032 Ed25519, seed 0x01..).
    const PK: [u8; 32] = hex32("8a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c");
    const DIGEST: [u8; 32] =
        hex32("b53e955af1d5617da7b94ef96e86db855f18df38592d0b262b1d06cca8e4a409");
    const SIG: &str = "2676cf78fe4d8e77fa43f4f92e829e109836ec6ceeb320ed2f98a18a8974db6de280aa4607b698366128ecfa3c9368fcbe16a0805d6af5bed95b1868e387520e";

    const fn nib(c: u8) -> u8 {
        match c {
            b'0'..=b'9' => c - b'0',
            b'a'..=b'f' => c - b'a' + 10,
            _ => panic!("hex"),
        }
    }
    const fn hex32(s: &str) -> [u8; 32] {
        let b = s.as_bytes();
        let mut o = [0u8; 32];
        let mut i = 0;
        while i < 32 {
            o[i] = nib(b[2 * i]) << 4 | nib(b[2 * i + 1]);
            i += 1;
        }
        o
    }
    fn hexv(s: &str) -> Vec<u8> {
        s.as_bytes()
            .chunks(2)
            .map(|c| nib(c[0]) << 4 | nib(c[1]))
            .collect()
    }
    fn att(pk: &[u8], sig: &[u8]) -> Bytes {
        Bytes::from([pk, sig].concat())
    }

    fn setup() -> (TestVM, ReceiptProver, Address) {
        let vm = TestVM::default();
        let owner = vm.msg_sender();
        let mut c = ReceiptProver::from(&vm);
        c.constructor(owner).unwrap();
        (vm, c, owner)
    }

    #[test]
    fn valid_signature_from_allowlisted_attester() {
        let (_vm, mut c, _) = setup();
        let sig = hexv(SIG);
        assert!(
            !c.verify(FixedBytes(DIGEST), att(&PK, &sig)),
            "not yet allowlisted"
        );
        c.set_attester(FixedBytes(PK), true).unwrap();
        assert!(c.verify(FixedBytes(DIGEST), att(&PK, &sig)));
    }

    #[test]
    fn rejects_tampered_digest_sig_and_length() {
        let (_vm, mut c, _) = setup();
        c.set_attester(FixedBytes(PK), true).unwrap();
        let sig = hexv(SIG);
        let mut d = DIGEST;
        d[0] ^= 1;
        assert!(!c.verify(FixedBytes(d), att(&PK, &sig)));
        let mut bad = sig.clone();
        bad[10] ^= 1;
        assert!(!c.verify(FixedBytes(DIGEST), att(&PK, &bad)));
        assert!(!c.verify(FixedBytes(DIGEST), Bytes::from(sig.clone())));
        assert!(!c.verify(FixedBytes(DIGEST), Bytes::new()));
        // non-canonical S (S + L) must be rejected (malleability)
        let mut hi = sig.clone();
        hi[63] |= 0xf0;
        assert!(!c.verify(FixedBytes(DIGEST), att(&PK, &hi)));
    }

    #[test]
    fn batch() {
        let (_vm, mut c, _) = setup();
        c.set_attester(FixedBytes(PK), true).unwrap();
        let a = att(&PK, &hexv(SIG));
        assert!(c.verify_batch(vec![FixedBytes(DIGEST); 3], vec![a.clone(); 3]));
        assert!(!c.verify_batch(vec![FixedBytes(DIGEST); 3], vec![a.clone(); 2]));
        let mut d = DIGEST;
        d[5] ^= 1;
        assert!(!c.verify_batch(vec![FixedBytes(DIGEST), FixedBytes(d)], vec![a.clone(), a]));
    }

    /// Same 100 fixtures the Solidity baseline and the on-chain benchmark use.
    #[test]
    fn accepts_all_shared_benchmark_vectors() {
        let f: serde_json::Value =
            serde_json::from_str(include_str!("../../../benchmarks/fixtures/vectors.json"))
                .unwrap();
        let (_vm, mut c, _) = setup();
        let pk = hexv(&f["ed25519Pubkey"].as_str().unwrap()[2..]);
        c.set_attester(FixedBytes::from_slice(&pk), true).unwrap();
        let digests = f["digests"].as_array().unwrap();
        let atts = f["ed25519"].as_array().unwrap();
        assert_eq!(digests.len(), 100);
        let d: Vec<FixedBytes<32>> = digests
            .iter()
            .map(|x| FixedBytes::from_slice(&hexv(&x.as_str().unwrap()[2..])))
            .collect();
        let a: Vec<Bytes> = atts
            .iter()
            .map(|x| Bytes::from(hexv(&x.as_str().unwrap()[2..])))
            .collect();
        assert!(c.verify_batch(d.clone(), a.clone()));
        // shifted pairing must fail
        let mut shifted = a.clone();
        shifted.rotate_left(1);
        assert!(!c.verify_batch(d, shifted));
    }

    #[test]
    fn only_owner_admin() {
        let (vm, mut c, _) = setup();
        vm.set_sender(Address::repeat_byte(0x42));
        assert!(c.set_attester(FixedBytes(PK), true).is_err());
        assert!(c.transfer_ownership(Address::repeat_byte(0x42)).is_err());
    }
}
